services:
  - type: web
    name: shuttletime
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: shuttletime
    plan: free
